services:
  mosquitto:
    image: eclipse-mosquitto:latest # Use the latest official Mosquitto image
    container_name: mosquitto_broker
    ports:
      - "1883:1883"  # Default MQTT port
      - "9001:9001"  # MQTT over WebSockets (useful for frontend later)
    volumes:
      - ./mosquitto/config:/mosquitto/config # Mounts a local config directory
      - ./mosquitto/data:/mosquitto/data     # Mounts a local data directory for persistence
      - ./mosquitto/log:/mosquitto/log       # Mounts a local log directory
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: solarrally_backend
    ports:
      - "8000:8000"  # FastAPI application port
    environment:
      - MQTT_BROKER_HOST=mosquitto  # Use service name for inter-container communication
      - MQTT_BROKER_PORT=1883
      - PYTHONPATH=/app
    depends_on:
      - mosquitto
    volumes:
      - ./backend:/app  # Mount source code for development (hot reload)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3